---
batch_size: 256
num_epoch: 120
dataset: 'imagenet'
num_classes: 1000
crop_size: 224
crop_interpolation: 2 ### 2: BILINEAR, 3:CUBIC
use_cosine_lr: True  ###
cosine_lr_min: 0.0
warmup_epochs: 5
lr: 0.1
lr_scale_factor: 256
lr_milestones: [30, 60, 90, 100]
momentum: 0.9
wd: 0.0001
nesterov: False
activation_mode: 0 ### 1: leakyReLU, 2: ReLU6, other: ReLU
init_mode: 'kaiming'
norm_name: 'BatchNorm2d'
norm_groups: 0
norm_k: [10, 10, 20, 20] ### per stage
norm_attention_mode: 2
norm_zero_gamma_init: False
dataaug:
    imagenet_extra_aug: False ### ColorJitter and PCA
    labelsmoothing_rate: 0.0
    mixup_rate: 0.0
stem:
    imagenet_head7x7: False
    replace_maxpool_with_res_bottleneck: False
aognet:
    max_split: [2, 2, 2, 2]
    extra_node_hierarchy: [4, 4, 4, 4] ### 0: none, 4: lateral connection
    remove_symmetric_children_of_or_node: [1, 2, 1, 2] ### if true, aog structure is much simplified and bigger filters and more units can be used
    terminal_node_no_slice: [0, 0, 0, 0]
    stride: [1, 2, 2, 2]
    drop_rate: [0.0, 0.0, 0.1, 0.1]
    bottleneck_ratio: 0.25
    handle_dbl_cnt: True
    handle_tnode_dbl_cnt: False
    handle_dbl_cnt_in_param_init: False
    use_group_conv: False
    width_per_group: 0
    when_downsample: 1
    replace_stride_with_avgpool: True ### in shortcut
    use_elem_max_for_ORNodes: False
    filter_list: [32, 128, 256, 512, 824] ### try to keep 1:4:2:2 ... except for the final stage which can be adusted for fitting the model size
    out_channels: [0, 0]
    blocks: [2, 2, 2, 1]
    dims: [2, 2, 4, 4]



